language: php
dist: trusty
matrix:
  include:
    - php: 7.2
    - php: 7.3
before_script:
  - composer validate
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
script:
  - vendor/bin/phpunit tests flush=1
